### ISSUE TITLE
I can't clone: invalid path 'tools /kafka/README.md'

### ISSUE THREAD

**Issue by i-plaza** [thingsboard/thingsboard-ce-k8s#124]
Hi,

I have problems cloning this project. The blank space in tools / . Can you remove it?

`git clone -b release-3.6.4 https://github.com/thingsboard/thingsboard-ce-k8s.git
Cloning into 'thingsboard-ce-k8s'...
remote: Enumerating objects: 2119, done.
remote: Counting objects: 100% (932/932), done.
remote: Compressing objects: 100% (241/241), done.
remote: Total 2119 (delta 772), reused 733 (delta 690), pack-reused 1187 eceiving objects:  98% (
Receiving objects: 100% (2119/2119), 372.58 KiB | 4.54 MiB/s, done.
Resolving deltas: 100% (1517/1517), done.
error: invalid path 'tools /kafka/README.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'`

**Comment by granaderainer** [comment]
Have the same issue.
Seems to be only a problem on Windows machines.
